# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyMoviesListApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMoviesListApp

  # - Networking
  pod 'Moya'
  pod 'ObjectMapper', '~> 2.2'

  # - Code Styling
  pod 'SwiftLint'

  # - UI
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'KVNProgress'

  # - Security
  pod 'SwiftKeychainWrapper'

  # - Images
  pod 'Kingfisher'

  # - DI
  #pod 'Swinject', '~> 2.0'

  # - Testing
  #pod 'OHHTTPStubs'
  #pod 'OHHTTPStubs/Swift'

  target 'MyMoviesListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMoviesListAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
